### ISSUE TITLE
NYT-single dataset missing

### ISSUE THREAD

**Issue by ardellelee** [yubowen-ph/JointER#2]
Hi! I've read your paper last year and it's really nice work. Good news that your paper got accepted to ECAI. Congratulations!

Also, thank you for releasing the code. But I noticed that the NYT-single dataset is missing in the repo. Would you provide the pre-processed data, or the pre-processing script? A reference link to external source is also helpful.

Thanks,
AL

**Comment by yubowen-ph** [comment]
Hi, 
Thanks for your interest in this work. You can obtain NYT-single from https://drive.google.com/drive/folders/0B--ZKWD8ahE4UktManVsY1REOUk?usp=sharing. I choosed not to add the NYT-single dataset into this repo because I believe it is really not a good benchmark for joint extraction. As pointed out in Section 3.2.1, many overlapping relations are not annotated in the test data of NYT-single, so I think it is meaningless to make comparison on NYT-single, and I also suggest you abandon this dataset. 

Best regards,
Yu Bowen

**Comment by ardellelee** [comment]
Hi Bowen,

Thank you. I agree that missing annotations in test set make the evaluation less meaningful, since any good joint extraction model tends to extract more correct triplets than annotated thus leads to lower precision. I requested the data for a further result analysis as my boss asked me to do so.

I will close this issue.

AL
